FLINT: stepsize Module Reference
stepsize Module Reference
StepSize Module.
Functions/Subroutines
pure subroutine stepsz0hairer (h, p, n, X0, Y0, F0, Sc, hSign, hMax, FCalls, pDiffEqSys, Params)
Subroutine for computing the starting step size using Hairer's algorithm.
pure real(wp) function stepszhairer (h, IsStepRejected, q, e, StepSzParams)
Pure function for computing the new step size using Hairer's algorithm.
Variables
real(wp), parameter sf = 0.9_WP
Safety factor.
real(wp), parameter sfmin = 0.333_WP
Minimum safety factor, so we dont decrease the step size too fast.
real(wp), parameter sfmax = 6.0_WP
Maximum safety factor, so we dont increase the step size too fast.
real(wp), parameter beta = 0.0_WP
beta for Lund stabilization Positive values (< 0.04) make the step size control more stable
real(wp), parameter hbyhoptold = 1.0e-4_WP
Also for Lund stabilization (see Hairer's code)
Detailed Description
StepSize Module.
This module provides procedures for step size computation.
Author
Bharat Mahajan
Date
01/28/2019 Module containing all the algorithms for step size computations
Function/Subroutine Documentation
stepsz0hairer()
pure subroutine stepsize::stepsz0hairer (real(wp), intent(out) h, integer, intent(in) p, integer, intent(in) n, real(wp), intent(in) X0, real(wp), dimension(n), intent(in) Y0, real(wp), dimension(n), intent(in) F0, real(wp), dimension(n), intent(in) Sc, real(wp), intent(in) hSign, real(wp), intent(in) hMax, integer, intent(out) FCalls, class(diffeqsys), intent(in), pointer pDiffEqSys, real(wp), dimension(:), intent(in), optional Params)
Subroutine for computing the starting step size using Hairer's algorithm.
For details on the algorithm, see Hairer's book "Solving ODE I" or his code dop853.f at http://www.unige.ch/~hairer/prog/nonstiff/dop853.f.
Parameters
[out] h Computed step size
[in] p Order of the method, which is used to advance the integration. For example, for Dormand-Prince 8(7) ERK method, p=8.
[in] n dimension of the DiffEq system
[in] x0 Initial value of the independent variable
[in] y0 Initial condition
[in] f0 DiffEq Function evaluated at Y0
[in] sc Error Scale factor
[in] hsign Must be either +1.0 or -1.0 depending on the forward or backward integration, respectively
[in] hmax Maximum allowed step size
[out] fcalls Number of Calls that this routine makes to DiffEq function "F"
[in] params Real parameter array to be passed to DEFunc
Remarks
The equation to solve for the new guess for the starting step size is
In Hairer's dop853 code, he actually uses instead of as the power of for reasons unknown. He uses for his dop853.
Definition at line 55 of file StepSz.f90.
stepszhairer()
pure real(wp) function stepsize::stepszhairer (real(wp), intent(in) h, logical, intent(in) IsStepRejected, integer, intent(in) q, real(wp), intent(in) e, real(wp), dimension(5), intent(in) StepSzParams)
Pure function for computing the new step size using Hairer's algorithm.
For details on the algorithm, see Hairer's book "Solving ODE I" or his code dop853.f at http://www.unige.ch/~hairer/prog/nonstiff/dop853.f.
Parameters
[in] h current step size
[in] issteprejected If true then the step size is decreased else increased.
[in] q q = min(p,phat) but Hairer uses q=8 in DOP853.
[in] e Error norm
Remarks
Optimal step computed using the equations:
New step chosen such that
New step chosen such that
Definition at line 125 of file StepSz.f90.
References beta, hbyhoptold, sf, sfmax, and sfmin.
Variable Documentation
beta
real(wp), parameter stepsize::beta = 0.0_WP
beta for Lund stabilization Positive values (< 0.04) make the step size control more stable
Definition at line 42 of file StepSz.f90.
Referenced by stepszhairer().
hbyhoptold
real(wp), parameter stepsize::hbyhoptold = 1.0e-4_WP
Also for Lund stabilization (see Hairer's code)
Definition at line 45 of file StepSz.f90.
Referenced by stepszhairer().
sf
real(wp), parameter stepsize::sf = 0.9_WP
Safety factor.
Definition at line 32 of file StepSz.f90.
Referenced by stepszhairer().
sfmax
real(wp), parameter stepsize::sfmax = 6.0_WP
Maximum safety factor, so we dont increase the step size too fast.
Definition at line 38 of file StepSz.f90.
Referenced by stepszhairer().
sfmin
real(wp), parameter stepsize::sfmin = 0.333_WP
Minimum safety factor, so we dont decrease the step size too fast.
Definition at line 35 of file StepSz.f90.
Referenced by stepszhairer().